# Generated by Django 5.2.7 on 2025-10-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Barisal', 'Barisal'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet'), ('Mymansing', 'Mymansing')], max_length=50),
        ),
    ]
